# Generated by Django 4.1.3 on 2022-11-13 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customer_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderapp',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateTimeField(null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='num',
            field=models.IntegerField(verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='price_all',
            field=models.IntegerField(verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.product', verbose_name='محصولات'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
