# Generated by Django 4.1.3 on 2022-11-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_orderapp_options_customer_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام شهر')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ManyToManyField(to='myapp.city', verbose_name='شهر'),
        ),
    ]
